services:
  vite_docker:
    image: node:20-alpine
    command: sh -c 'npm install && npm run dev'
    container_name: to-do-list-with-pair-programming
    # entrypoint: /bin/sh
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
